export const TOPIC_POINT_REGISTRY = {
  'bloc-5': {
    'tema-16': [
      'Concepte i funcions del pressupost public',
      'Principis pressupostaris en el sector public',
      'Marc constitucional del pressupost public',
      'Marc estatutari i normatiu del pressupost de la Generalitat',
      'El pressupost com a instrument de planificacio economica',
      'Estructura del pressupost de la Generalitat',
      'Classificacio organica del pressupost',
      'Classificacio economica del pressupost',
      'Classificacio funcional i per programes',
      'El cicle pressupostari',
      'Elaboracio del pressupost de la Generalitat',
      "Organs competents en l'elaboracio del pressupost",
      'Avantprojecte de pressupost',
      'Projecte de llei de pressupostos',
      'Tramitacio parlamentaria del pressupost',
      'Aprovacio de la llei de pressupostos',
      'Prorroga pressupostaria',
      'Modificacions pressupostaries',
      'Transferencies de credit',
      'Generacions de credit',
      'Credits extraordinaris i suplements de credit',
      "Principi d'estabilitat pressupostaria",
      'Regles fiscals i sostenibilitat financera',
      'Control i seguiment del pressupost',
    ],
    'tema-17': [
      "Concepte d'execucio pressupostaria",
      "Principis que regeixen l'execucio de la despesa publica",
      'Fases del procediment de despesa publica',
      'Autoritzacio de la despesa',
      'Disposicio o compromis de la despesa',
      "Reconeixement de l'obligacio",
      'Ordenacio del pagament',
      'Pagament material de la despesa',
      "Documents comptables en l'execucio de la despesa",
      'Organs competents en la gestio de la despesa',
      'Control previ de la despesa',
      'Gestio de pagaments',
      'Pagaments a justificar',
      'Bestretes de caixa fixa',
      'Despeses pluriennals',
      'Despeses anticipades',
      "Execucio del pressupost d'ingressos",
      'Reconeixement de drets economics',
      'Gestio recaptatoria',
      'Anullacio i cancellacio de drets',
      'Relacio entre execucio pressupostaria i comptabilitat publica',
      'Tancament de l\'exercici pressupostari',
      'Liquidacio del pressupost',
      "Informacio i seguiment de l'execucio pressupostaria",
    ],
    'tema-18': [
      "Concepte de control de l'activitat economica publica",
      'Principis del control financer public',
      'Tipus de control en el sector public',
      'Control intern',
      'Funcio interventora',
      'Control financer permanent',
      'Auditoria publica',
      'Organs de control intern de la Generalitat',
      'La Intervencio General de la Generalitat',
      'Control extern del sector public',
      'La Sindicatura de Comptes de Catalunya',
      'Relacio amb el Tribunal de Comptes',
      'Objectius del control financer',
      'Procediments de control financer',
      'Informes de control',
      'Seguiment de recomanacions',
      'Responsabilitat comptable',
      'Responsabilitat administrativa',
      'Responsabilitat disciplinaria',
      'Responsabilitat penal en la gestio publica',
      'Procediments de responsabilitat comptable',
      'Exigencia de responsabilitats',
      'Prevencio del frau en la gestio publica',
      'Transparencia i rendicio de comptes',
    ],
  },
  'bloc-6': {
    'tema-19': [
      "Concepte d'empleat public",
      'Marc constitucional de la funcio publica',
      "Marc normatiu de l'ocupacio publica",
      "Principis rectors de l'acces a l'ocupacio publica",
      "Classes d'empleats publics",
      'Funcionaris de carrera',
      'Funcionaris interins',
      "Personal laboral al servei de l'Administracio",
      'Personal eventual',
      'Directius publics professionals',
      'Grups de classificacio professional dels funcionaris',
      "Requisits per accedir a l'ocupacio publica",
      'Sistemes de seleccio de personal',
      'Procediments selectius',
      'Adquisicio de la condicio de funcionari',
      'Perdua de la condicio de funcionari',
      'Provisio de llocs de treball',
      'Mobilitat dels empleats publics',
      'Carrera professional',
      "Avaluacio de l'acompliment",
      'Planificacio dels recursos humans',
      'Registres de personal',
      "Instruments d'ordenacio del personal",
      'Principis etics i de conducta dels empleats publics',
    ],
    'tema-20': [
      'Concepte de drets dels empleats publics',
      'Drets individuals dels empleats publics',
      'Drets exercits col-lectivament',
      'Dret a la carrera professional',
      'Dret a la formacio',
      'Dret a la conciliacio de la vida personal i laboral',
      'Dret a la proteccio en materia de seguretat i salut laboral',
      'Dret a la negociacio col-lectiva',
      'Dret de representacio i participacio',
      'Dret de vaga',
      'Deures dels empleats publics',
      'Principis de conducta professional',
      'Principis etics del servei public',
      'Incompatibilitats dels empleats publics',
      'Concepte de situacio administrativa',
      'Servei actiu',
      'Serveis especials',
      'Servei en altres administracions publiques',
      'Excedencia voluntaria',
      'Excedencia forcosa',
      'Excedencia per cura de familiars',
      'Suspensio de funcions',
      'Reingres al servei actiu',
      'Efectes de les situacions administratives',
    ],
    'tema-21': [
      'Concepte de regim disciplinari',
      'Principis del regim disciplinari',
      'Principi de legalitat i tipicitat',
      'Responsabilitat disciplinaria dels empleats publics',
      'Classificacio de les infraccions disciplinaries',
      'Faltes molt greus',
      'Faltes greus',
      'Faltes lleus',
      'Sancions disciplinaries',
      'Tipus de sancions aplicables',
      'Proporcionalitat de les sancions',
      'Prescripcio de les faltes',
      'Prescripcio de les sancions',
      'Procediment disciplinari',
      'Inici del procediment disciplinari',
      'Instruccio del procediment',
      "Dret de defensa de l'interessat",
      'Proposta de resolucio',
      'Resolucio del procediment disciplinari',
      'Execucio de les sancions',
      'Mesures provisionals',
      'Responsabilitat penal i disciplinaria',
      'Control jurisdiccional de les sancions disciplinaries',
      'Garanties en el procediment disciplinari',
    ],
  },
  'bloc-7': {
    'tema-22': [
      "Concepte de transparencia en l'Administracio publica",
      'Principis de transparencia en el sector public',
      'Marc constitucional de la transparencia',
      'Marc normatiu de la transparencia a Catalunya',
      'La Llei de transparencia de Catalunya',
      'Subjectes obligats a la transparencia',
      'Ambit subjectiu de la llei de transparencia',
      "Dret d'acces a la informacio publica",
      "Titulars del dret d'acces",
      "Limits al dret d'acces a la informacio",
      "Procediment d'acces a la informacio publica",
      "Resolucio de les sollicituds d'acces",
      'Silenci administratiu en materia de transparencia',
      'Publicitat activa',
      'Continguts de la publicitat activa',
      'Portal de transparencia',
      'Bon govern i principis etics',
      'Codis de conducta dels carrecs publics',
      'Responsabilitat per incompliment de les obligacions de transparencia',
      'El Consell de Transparencia de Catalunya',
      'Reclamacions davant el Consell de Transparencia',
      'Control i supervisio de la transparencia',
      'Participacio ciutadana i transparencia',
      'Impacte de la transparencia en la qualitat democratica',
    ],
    'tema-23': [
      'Concepte de proteccio de dades personals',
      'Marc normatiu europeu de proteccio de dades',
      'El Reglament General de Proteccio de Dades (RGPD)',
      'La Llei Organica de Proteccio de Dades i Garantia dels Drets Digitals',
      'Principis del tractament de dades personals',
      'Licitud del tractament de dades',
      'Categories de dades personals',
      'Dades especialment protegides',
      'Drets de les persones interessades',
      "Dret d'acces",
      'Dret de rectificacio',
      'Dret de supressio',
      "Dret d'oposicio",
      'Dret a la limitacio del tractament',
      'Dret a la portabilitat de les dades',
      'Responsable del tractament',
      'Encarrec del tractament',
      'Delegat de proteccio de dades',
      "Registre d'activitats de tractament",
      'Mesures de seguretat en el tractament de dades',
      'Violacions de seguretat de les dades',
      'Autoritats de control en proteccio de dades',
      'Regim sancionador en proteccio de dades',
      'Proteccio de dades en les administracions publiques',
    ],
    'tema-24': [
      "Concepte d'administracio digital",
      "Principis de l'administracio electronica",
      "Marc normatiu de l'administracio electronica",
      'Drets digitals de la ciutadania',
      "Dret a relacionar-se electronicament amb l'Administracio",
      'Identificacio electronica',
      'Signatura electronica',
      'Certificats digitals',
      'Registre electronic',
      'Notificacions electroniques',
      'Expedient administratiu electronic',
      'Arxiu electronic de documents',
      'Interoperabilitat entre administracions',
      "Plataformes d'interoperabilitat",
      "Seguretat en l'administracio digital",
      'Esquema Nacional de Seguretat',
      "Esquema Nacional d'Interoperabilitat",
      'Seu electronica',
      'Carpeta ciutadana',
      'Tramitacio electronica de procediments',
      'Digitalitzacio dels serveis publics',
      "Intelligencia artificial en l'administracio publica",
      'Bretxa digital i inclusio digital',
      'Govern digital i transformacio digital del sector public',
    ],
    'tema-25': [
      "Concepte d'atencio a la ciutadania",
      "Principis d'atencio a la ciutadania",
      'Dret de la ciutadania a una bona administracio',
      "Canals d'atencio a la ciutadania",
      'Atencio presencial',
      'Atencio telefonica',
      'Atencio electronica',
      "Oficines d'atencio ciutadana",
      'Informacio administrativa',
      'Registre de documents',
      'Queixes i suggeriments',
      'Gestio de reclamacions',
      'Participacio ciutadana en els serveis publics',
      "Qualitat en l'Administracio publica",
      'Models de gestio de qualitat',
      'Cartes de serveis',
      'Avaluacio de la qualitat dels serveis',
      'Indicadors de qualitat',
      'Millora continua dels serveis publics',
      'Simplificacio administrativa',
      'Accessibilitat dels serveis publics',
      'Administracio centrada en la ciutadania',
      'Innovacio en la gestio publica',
      'Avaluacio de la satisfaccio ciutadana',
    ],
  },
};

export const getTopicPointTitles = (blocId, temaId) => {
  return TOPIC_POINT_REGISTRY?.[blocId]?.[temaId] || [];
};
